### ISSUE TITLE
User in DB anlegen

### ISSUE THREAD

**Issue by Finneah** [Finneah/heppiventcard#5]
## Stand
Die User DB gibt es schon. 

## TODO
- [ ] insert beim eingeben
- [ ] update beim ändern
- [ ] get beim app start
